insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (1, '19:10', '6/28/2022', 15, 'Oklahoma', true, 'pbleackley0@de.vu');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (2, '22:10', '2/28/2023', 15, 'California', false, 'mhuckerbe1@state.tx.us');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (3, '10:22', '10/6/2022', 12, 'Florida', true, 'jlangstone2@house.gov');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (4, '2:47', '12/13/2022', 1, 'New York', true, 'giverson3@fda.gov');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (5, '14:22', '11/8/2022', 16, 'California', false, 'eromaines4@photobucket.com');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (6, '2:01', '9/24/2022', 6, 'New York', false, 'jmedgewick5@patch.com');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (7, '13:33', '3/22/2023', 12, 'Florida', false, 'ssumers6@nymag.com');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (8, '12:22', '11/9/2022', 8, 'Wyoming', false, 'mgianinotti7@google.fr');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (9, '6:04', '1/27/2023', 19, 'New York', false, 'lchavey8@blogger.com');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (10, '14:57', '12/27/2022', 11, 'California', true, 'imcgillecole9@jugem.jp');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (11, '0:39', '8/8/2022', 6, 'Florida', true, 'msteventona@statcounter.com');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (12, '13:17', '10/14/2022', 12, 'Alabama', false, 'strottonb@google.ru');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (13, '17:03', '6/22/2022', 18, 'Massachusetts', true, 'clarouxc@pbs.org');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (14, '8:30', '3/7/2023', 15, 'California', false, 'jrobelowd@google.pl');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (15, '9:27', '4/29/2022', 7, 'Arkansas', true, 'rwildse@photobucket.com');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (16, '22:24', '3/1/2023', 19, 'California', true, 'lpaasof@infoseek.co.jp');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (17, '2:59', '12/23/2022', 9, 'California', false, 'rcranmerg@wordpress.org');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (18, '22:29', '4/26/2022', 11, 'Kansas', true, 'dschankelh@ezinearticles.com');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (19, '9:22', '9/7/2022', 15, 'Arizona', false, 'elammingi@bigcartel.com');
insert into sightings (id, time_sighted, date_sighted, individual, location, healthy, sighter) values (20, '0:30', '9/2/2022', 7, 'Missouri', false, 'myedallj@ebay.com');